spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:xxxxxxx?characterEncoding=utf-8&useSSL=false
    username: xxxxxxx
    password: xxxxxxx

server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
#  instance:
#    hostname: product