server:
  port: 10002
eureka:
  instance:
    hostname: order
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:xxxxxxxx?characterEncoding=utf-8&useSSL=false
    username: xxxxxx
    password: xxxxxx

#  application:
#    name: order
mybatis:
  mapper-locations: "classpath*:mapper/*Mapper.xml"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

